name: Tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup Node
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run coverage
        run: npm run coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '10.x'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1 
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '10.x'
